version: "3.7"

services:
  database_merge:
    image: postgres
    container_name: database_merge
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=merge
      - POSTGRES_DB=merge_skill
    volumes: 
    - pgdata:/data/postgres
    networks:
      - app-network
  app:
    build: .
    container_name: merge-skill
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - app-network

networks: 
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local